services:
  # Web Application (PHP/Apache)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor